name: C++ Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Visual Studio Build Tools 2019
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild /p:Configuration=Release

    - name: Run Code Analysis
      uses: microsoft/CodeAnalysis@v1
      with:
        solution: 'MySolution.sln'
        build_platform: 'x64'
        build_configuration: 'Release'
        analysis_ruleset: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\TeamTools\Static Analysis Tools\\Rule Sets\CppCoreCheckRules.ruleset'
        analysis_toolset: 'v142'
        output_directory: '$(Build.SourcesDirectory)\CodeAnalysisOutput'
